---
# tasks file for packages
- name: Update package cache
  apt:
    update_cache: yes

- name: Read Package list
  set_fact:
    package_list: "{{ lookup('file', 'package_list.txt') }}"

- name: Install packages 
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list.split('\n') }}"
