---
# tasks file for elk_stack

- name: Create ELK Stack directory
  file:
    path: /opt/elk_stack
    state: directory

#- name: Git clone
#  command: git clone https://github.com/deviantony/docker-elk.git
#  args:
#    chdir: /opt/elk_stack 

- name: Docker Compose
  docker_compose:
    project_src: /opt/elk_stack/docker_elk
    state: present
    build: yes

